
<div class="blue-gradient z-depth-2">
	<div class="page-header" >
		<h1 style="padding: 15px">DASHBOARD</h1> 
	</div>
</div>
<br>


<div class="row">
	<div class="col-md-4">
			<div class="card card-cascade">
			  <div class="view view-cascade gradient-card-header blue-gradient">
			    <h2 class="card-header-title mb-3">Ingresos Mensuales por disciplinas</h2>
<!--			    <p class="card-header-subtitle mb-0"></p>			-->
			  </div>
			  <div class="card-body card-body-cascade text-center" id="div_graf_ingreso_disciplinas">			
			 	 
			 </div>			
			</div>
	</div>
</div>


<script>
dashboard();
</script>