
<div class="blue-gradient z-depth-2">
	<div class="page-header" >
		<h1 style="padding: 15px">DASHBOARD</h1> 
	</div>
</div>
<br>


<div class="row">
	<div class="col-md-3">
		<div class="card card-cascade">
		  <div class="view view-cascade gradient-card-header blue-gradient">
		    <h5 class="card-header-title mb-1">Clientes Activos</h5>
		  </div>
		  <div class="card-body card-body-cascade text-center h-30" id="div_graf_clientes_activos">			
		 	 
		 </div>			
		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-cascade">
		  <div class="view view-cascade gradient-card-header blue-gradient">
		    <h5 class="card-header-title mb-1">Ingresos Mensuales</h5>
		  </div>
		  <div class="card-body card-body-cascade text-center h-30" id="div_graf_ingreso_disciplinas">			
		 	 
		 </div>			
		</div>
	</div>
</div>
<br></br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-cascade">
		  <div class="view view-cascade gradient-card-header blue-gradient">
		    <h5 class="card-header-title mb-1">INGRESOS DEL DIA</h5>
		  </div>
		  <div class="card-body card-body-cascade text-center h-30" id="div_graf_ingreso_del_dia_resumen">			
		 	 
		 </div>			
		</div>
	</div>
	
	<div class="col-md-6">
		<div class="card card-cascade">
		  <div class="view view-cascade gradient-card-header blue-gradient">
		    <h5 class="card-header-title mb-1">Membresias por vencer dentro de 30 dias</h5>
		  </div>
		  <div class="card-body card-body-cascade text-center h-30" id="div_graf_membresias_x_vencer">			
		 	 
		 </div>			
		</div>
	</div>
	<div class="col-md-3">
		<div class="card card-cascade">
		  <div class="view view-cascade gradient-card-header blue-gradient">
		    <h5 class="card-header-title mb-1">Por cobrar</h5>
		  </div>
		  <div class="card-body card-body-cascade text-center h-30" id="div_graf_deudas_x_cobrar_resumen">			
		 	 
		 </div>			
		</div>
	</div>
</div>



<script>
dashboard();
</script>