<!-- --------------   Modal --------------  -->
  <div class="modal fade" id="modal_mantenimiento_disciplina" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="lb_title_modal"></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>          
        </div>
        <div class="modal-body">
        	<input type="hidden" id="hd_cod_xxx" value="">
        	
            <div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div class="md-form">												
					    <input type="text" id="txt_modal_disciplina_nombre" class="form-control">
					    <label for="txt_modal_disciplina_nombre" class="lbl">Nombre de Disciplina</label>
					</div>
				</div>
				<div class="col-md-1"></div>
			</div>	
			<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div class="md-form">												
					    <input type="text" id="txt_modal_disciplina_descripcion" class="form-control">
					    <label for="txt_modal_disciplina_descripcion" class="lbl">Descripcion de Disciplina</label>
					</div>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div class="md-form">												
					    <input type="color" id="txt_modal_disciplina_color" class="form-control">
					    <label for="txt_modal_disciplina_color" class="lbl">Descripcion de Disciplina</label>
					</div>
				</div>
				<div class="col-md-1"></div>
			</div>
				
        </div>
<!--        <div class="modal-footer">-->
<!--          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
<!--        </div>-->
      </div>
      
    </div>
  </div>
<!-- --------------   Modal --------------  -->

<div class="blue-gradient z-depth-2">
	<div class="page-header" >
		<h1 style="padding: 15px">Mantenimiento Disciplinas</h1> 
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div id='div_tbl_disciplinas'></div>
	</div>
	<div class="col-md-1"></div>
</div>

<script>
mantenimiento_disciplinas();
</script>