<!-- --------------   Modal --------------  -->
  <div class="modal fade" id="modal_clientes_clase_registro" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="lb_title_modal"></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>          
        </div>
        <div class="modal-body">
        	<input type="hidden" id="hd_cod_xxx" value="">
        	
            <div class="row">
				<div class="col-md-12">
				
				</div>				
			</div>		
        </div>
<!--        <div class="modal-footer">-->
<!--          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
<!--        </div>-->
      </div>
      
    </div>
  </div>
<!-- --------------   Modal --------------  -->

<div class="blue-gradient z-depth-2">
	<div class="page-header" >
		<h1 style="padding: 15px">TITULO PAGINA</h1> 
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="card" id='div_tbl_xxx'></div>
	</div>
	<div class="col-md-1"></div>
</div>

<script>
	mantenimiento_xxx();
</script>