<!-- --------------   Modal --------------  -->
  <div class="modal fade" id="modal_mantenimiento_sede" role="dialog">
    <div class="modal-dialog modal-sm">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="lb_title_modal_mantenimiento_sede">Mantenimiento de sedes</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>          
        </div>
        <div class="modal-body">
        	<input type="hidden" id="hd_modal_sede_codigo" value="">
        	
            <div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div class="md-form">												
					    <input type="text" id="txt_modal_sede_nombre" class="form-control">
					    <label for="txt_modal_sede_nombre" class="lbl_active">Nombre de Sede</label>
					</div>
				</div>
				<div class="col-md-1"></div>
			</div>	
			<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div class="md-form">												
					    <input type="text" id="txt_modal_sede_direccion" class="form-control">
					    <label for="txt_modal_sede_direccion" class="lbl_active">Direcci&oacute;n de Sede</label>
					</div>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<div class="md-form">												
					    <label for="cb_modal_sede_estado" class="active">Estado</label>
					    <select class="selectpicker" id="cb_modal_sede_estado" data-size="2" data-live-search="false" data-width="100%" data-actions-box="false">
      						<option value="1" selected='selected'>Activa</option>
							<option value="0">Anulada</option>
    					</select>
					</div>
				</div>
				<div class="col-md-1"></div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">
					<button type="button" class="btn btn-primary" onclick="mantenimiento_sede_modal_guardar()" >Guardar</button>
				</div>						
			</div>	
        </div>
<!--        <div class="modal-footer">-->
<!--          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
<!--        </div>-->
      </div>
      
    </div>
  </div>
<!-- --------------   Modal --------------  -->

<div class="blue-gradient z-depth-2">
	<div class="page-header" >
		<h1 style="padding: 15px">Mantenimiento Sedes</h1> 
	</div>
</div>
<br>


<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10">
		<div id='div_tbl_sedes'></div>
	</div>
	<div class="col-md-1"></div>
</div>

<script>
mantenimiento_sedes();
</script>